from operator import attrgetter
from pathlib import Path
from textwrap import dedent
from typing import Any

import pytest
import requests_mock
from _pytest.monkeypatch import MonkeyPatch
from requests_mock import Mocker

from diff_poetry_lock import __version__
from diff_poetry_lock.github_api import MAGIC_COMMENT_IDENTIFIER, GithubApi
from diff_poetry_lock.run_poetry import PackageSummary, diff, do_diff, format_comment, load_packages, main
from diff_poetry_lock.settings import (
    GitHubActionsSettings,
    Settings,
    VelaSettings,
)

TESTFILE_1 = Path("diff_poetry_lock/test/res/poetry1.lock")
TESTFILE_2 = Path("diff_poetry_lock/test/res/poetry2.lock")


@pytest.fixture
def cfg() -> Settings:
    return create_settings()


@pytest.fixture
def data1() -> bytes:
    return load_file(TESTFILE_1)


@pytest.fixture
def data2() -> bytes:
    return load_file(TESTFILE_2)


def test_settings(monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("GITHUB_EVENT_NAME", "pull_request")
    monkeypatch.setenv("GITHUB_REF", "refs/pull/42/merge")
    monkeypatch.setenv("GITHUB_HEAD_REF", "use-github-package")
    monkeypatch.setenv("GITHUB_REPOSITORY", "account/repo")
    monkeypatch.setenv("INPUT_GITHUB_TOKEN", "foobar")
    monkeypatch.setenv("GITHUB_BASE_REF", "main")

    s = GitHubActionsSettings()
    assert s.event_name == "pull_request"
    assert s.ref == "refs/pull/42/merge"
    assert s.head_ref == "use-github-package"
    assert s.repository == "account/repo"
    assert s.base_ref == "main"
    assert s.pr_num == "42"


def test_vela_settings(monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("VELA_BUILD_EVENT", "push")
    monkeypatch.setenv("VELA_BUILD_REF", "refs/pull/42/head")
    monkeypatch.setenv("VELA_REPO_FULL_NAME", "account/repo")
    monkeypatch.setenv("VELA_REPO_BRANCH", "main")
    monkeypatch.setenv("PARAMETER_GITHUB_TOKEN", "vela-token")
    monkeypatch.setenv("PARAMETER_LOCKFILE_PATH", "poetry.lock")
    monkeypatch.setenv("PARAMETER_GITHUB_API_URL", "https://api.github.com")

    s = VelaSettings()
    assert s.event_name == "push"
    assert s.ref == "refs/pull/42/head"
    assert s.repository == "account/repo"
    assert s.base_ref == "refs/heads/main"
    assert s.pr_num == "42"


def test_settings_not_pr(monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("GITHUB_EVENT_NAME", "push")
    monkeypatch.setenv("GITHUB_REF", "refs/heads/deps-update")
    monkeypatch.setenv("GITHUB_HEAD_REF", "deps-update")
    monkeypatch.setenv("GITHUB_REPOSITORY", "account/repo")
    monkeypatch.setenv("INPUT_GITHUB_TOKEN", "foobar")
    monkeypatch.setenv("GITHUB_BASE_REF", "main")

    with pytest.raises(SystemExit) as pytest_wrapped_e:
        main()

    assert pytest_wrapped_e.type is SystemExit
    assert pytest_wrapped_e.value.code == 0


def test_diff() -> None:
    old = load_packages(TESTFILE_1)
    new = load_packages(TESTFILE_2)

    summary: list[PackageSummary] = sorted(diff(old, new), key=attrgetter("name"))

    expected = [
        PackageSummary(name="certifi", old_version="2022.12.7", new_version="2022.12.7"),
        PackageSummary(name="charset-normalizer", old_version="3.1.0", new_version="3.1.0"),
        PackageSummary(name="idna", old_version="3.4", new_version="3.4"),
        PackageSummary(name="pydantic", old_version="1.10.6", new_version=None),
        PackageSummary(name="requests", old_version="2.28.2", new_version="2.28.2"),
        PackageSummary(name="typing-extensions", old_version="4.5.0", new_version=None),
        PackageSummary(name="urllib3", old_version="1.26.15", new_version="1.26.14"),
    ]
    assert summary == expected

    expected_comment = f"""\
    ### Detected 3 changes to dependencies in Poetry lockfile

    From base new-sha to head old-sha:

    Removed **pydantic** (1.10.6)
    Removed **typing-extensions** (4.5.0)
    Updated **urllib3** (1.26.15 -> 1.26.14)

    *(0 added, 2 removed, 1 updated, 4 not changed)*

    <small>Generated by diff-poetry-lock {__version__}</small>
    """
    assert (
        format_comment(
            summary,
            base_commit_hash="new-sha",
            head_commit_hash="old-sha",
        )
        or ""
    ).strip() == dedent(expected_comment).strip()


def test_diff_2() -> None:
    old = load_packages(TESTFILE_2)
    new = load_packages(TESTFILE_1)

    summary: list[PackageSummary] = sorted(diff(old, new), key=attrgetter("name"))

    expected = [
        PackageSummary(name="certifi", old_version="2022.12.7", new_version="2022.12.7"),
        PackageSummary(name="charset-normalizer", old_version="3.1.0", new_version="3.1.0"),
        PackageSummary(name="idna", old_version="3.4", new_version="3.4"),
        PackageSummary(name="pydantic", old_version=None, new_version="1.10.6"),
        PackageSummary(name="requests", old_version="2.28.2", new_version="2.28.2"),
        PackageSummary(name="typing-extensions", old_version=None, new_version="4.5.0"),
        PackageSummary(name="urllib3", old_version="1.26.14", new_version="1.26.15"),
    ]
    assert summary == expected

    expected_comment = f"""\
    ### Detected 3 changes to dependencies in Poetry lockfile

    From base new-sha to head old-sha:

    Added **pydantic** (1.10.6)
    Added **typing-extensions** (4.5.0)
    Updated **urllib3** (1.26.14 -> 1.26.15)

    *(2 added, 0 removed, 1 updated, 4 not changed)*

    <small>Generated by diff-poetry-lock {__version__}</small>
    """
    assert (
        format_comment(
            summary,
            base_commit_hash="new-sha",
            head_commit_hash="old-sha",
        )
        or ""
    ).strip() == dedent(expected_comment).strip()


def test_diff_no_changes() -> None:
    old = load_packages(TESTFILE_2)
    new = load_packages(TESTFILE_2)

    summary: list[PackageSummary] = sorted(diff(old, new), key=attrgetter("name"))

    expected = [
        PackageSummary(name="certifi", old_version="2022.12.7", new_version="2022.12.7"),
        PackageSummary(name="charset-normalizer", old_version="3.1.0", new_version="3.1.0"),
        PackageSummary(name="idna", old_version="3.4", new_version="3.4"),
        PackageSummary(name="requests", old_version="2.28.2", new_version="2.28.2"),
        PackageSummary(name="urllib3", old_version="1.26.14", new_version="1.26.14"),
    ]
    assert summary == expected
    assert format_comment(summary) is None


def test_file_loading_missing_file_base_ref(cfg: Settings) -> None:
    with requests_mock.Mocker() as m:
        m.get(
            f"{cfg.api_url}/repos/{cfg.repository}/contents/{cfg.lockfile_path}?ref={cfg.base_ref}",
            status_code=404,
        )

        with pytest.raises(FileNotFoundError):
            do_diff(cfg)


def test_file_loading_missing_file_head_ref(cfg: Settings, data1: bytes) -> None:
    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        m.get(
            f"{cfg.api_url}/repos/{cfg.repository}/contents/{cfg.lockfile_path}?ref={cfg.ref}",
            status_code=404,
        )

        with pytest.raises(FileNotFoundError):
            do_diff(cfg)


def test_e2e_no_diff_existing_comment(cfg: Settings, data1: bytes) -> None:
    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        mock_get_file(m, cfg, data1, cfg.ref)
        comments = [
            {"body": "foobar", "id": 1334, "user": {"id": 123}},
            {"body": "foobar", "id": 1335, "user": {"id": 41898282}},
            {"body": f"{MAGIC_COMMENT_IDENTIFIER}foobar", "id": 1337, "user": {"id": 41898282}},
        ]
        mock_list_comments(m, cfg, comments)
        m.delete(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/comments/1337",
        )

        do_diff(cfg)


def test_e2e_no_diff_inexisting_comment(cfg: Settings, data1: bytes) -> None:
    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        mock_get_file(m, cfg, data1, cfg.ref)
        mock_list_comments(m, cfg, [])

        do_diff(cfg)


def test_e2e_diff_inexisting_comment(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_2), load_packages(TESTFILE_1)),
        base_commit_hash="new-sha",
        head_commit_hash="old-sha",
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref, resolved_hash="old-sha")
        mock_get_file(m, cfg, data2, cfg.ref, resolved_hash="new-sha")
        mock_resolve_commit_hashes(m, cfg, head_hash="new-sha", base_hash="old-sha")
        mock_find_pr_for_branch(m, cfg, pr_num="1")
        mock_list_comments(m, cfg, [], pr_num="1")
        m.post(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/1/comments",
            json={"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}"},
        )

        do_diff(cfg)


def test_e2e_diff_existing_comment_same_data(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_1), load_packages(TESTFILE_2)),
        base_commit_hash="old-sha",
        head_commit_hash="new-sha",
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref, resolved_hash="old-sha")
        mock_get_file(m, cfg, data2, cfg.ref, resolved_hash="new-sha")
        mock_resolve_commit_hashes(m, cfg, head_hash="new-sha", base_hash="old-sha")
        mock_find_pr_for_branch(m, cfg, pr_num="1")
        comments = [
            {"body": "foobar", "id": 1334, "user": {"id": 123}},
            {"body": "foobar", "id": 1335, "user": {"id": 41898282}},
            {"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}", "id": 1337, "user": {"id": 41898282}},
        ]
        mock_list_comments(m, cfg, comments, pr_num="1")

        do_diff(cfg)


def test_e2e_diff_existing_comment_different_data(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_1), []),
        base_commit_hash="new-sha",
        head_commit_hash="old-sha",
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref, resolved_hash="old-sha")
        mock_get_file(m, cfg, data2, cfg.ref, resolved_hash="new-sha")
        mock_resolve_commit_hashes(m, cfg, head_hash="new-sha", base_hash="old-sha")
        mock_find_pr_for_branch(m, cfg, pr_num="1")
        comments = [
            {"body": "foobar", "id": 1334, "user": {"id": 123}},
            {"body": "foobar", "id": 1335, "user": {"id": 41898282}},
            {"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}", "id": 1337, "user": {"id": 41898282}},
        ]
        mock_list_comments(m, cfg, comments, pr_num="1")
        mock_issue_comment(m, cfg, 1337, f"{MAGIC_COMMENT_IDENTIFIER}{summary}")
        m.patch(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/comments/1337",
            json={"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}"},
        )

        do_diff(cfg)


def test_e2e_diff_commit_lookup_http_failure_falls_back_to_ref(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_2), load_packages(TESTFILE_1)),
        base_commit_hash=cfg.ref,
        head_commit_hash=cfg.base_ref,
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        mock_get_file(m, cfg, data2, cfg.ref)
        mock_find_pr_for_branch(m, cfg, pr_num="1")
        m.post(
            f"{cfg.api_url}/graphql",
            status_code=500,
        )
        mock_list_comments(m, cfg, [], pr_num="1")
        m.post(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/1/comments",
            json={"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}"},
        )

        do_diff(cfg)


def test_resolve_commit_hash_request_exception_returns_ref(cfg: Settings, monkeypatch: MonkeyPatch) -> None:
    api = GithubApi(cfg)

    def raise_timeout(*_args: object, **_kwargs: object) -> None:
        msg = "timeout"
        raise ValueError(msg)

    monkeypatch.setattr(api.requester, "graphql_query", raise_timeout)

    resolved_head, resolved_base = api.resolve_commit_hashes(cfg.ref, cfg.base_ref)
    assert resolved_head == cfg.ref
    assert resolved_base == cfg.base_ref


def test_resolve_commit_hash_cache_hit_uses_cached_value(cfg: Settings) -> None:
    api = GithubApi(cfg)

    with requests_mock.Mocker() as m:
        mock_resolve_commit_hashes(m, cfg, head_hash="cached-sha", base_hash="base-sha")
        resolved_head, resolved_base = api.resolve_commit_hashes(cfg.ref, cfg.base_ref)

    assert resolved_head == "cached-sha"
    assert resolved_base == "base-sha"


def test_resolve_commit_hash_cache_miss_returns_ref(cfg: Settings) -> None:
    api = GithubApi(cfg)

    with requests_mock.Mocker() as m:
        mock_resolve_commit_hashes(m, cfg)
        resolved_head, resolved_base = api.resolve_commit_hashes(cfg.ref, cfg.base_ref)
        assert resolved_head == cfg.ref
        assert resolved_base == cfg.base_ref


def load_file(filename: Path) -> bytes:
    with filename.open("rb") as f:
        return f.read()


def mock_find_pr_for_branch(m: Mocker, s: Settings, pr_num: str = "1") -> None:
    mock_repo(m, s)
    branch = s.ref.replace("refs/heads/", "")
    head = f"{s.repository.split('/')[0]}:{branch}"
    m.get(
        f"{s.api_url}/repos/{s.repository}/pulls?head={head}&state=open",
        json=[{"number": int(pr_num)}],
    )
    m.get(
        f"{s.api_url}/repos/{s.repository}/pulls?state=open&head={head}",
        json=[{"number": int(pr_num)}],
    )


def mock_list_comments(m: Mocker, s: Settings, response_json: list[dict[Any, Any]], pr_num: str = "1") -> None:
    mock_repo(m, s)
    mock_issue(m, s, pr_num=pr_num)
    comments_base_url = f"{s.api_url}/repos/{s.repository}/issues/{pr_num}/comments"
    m.get(
        f"{comments_base_url}?per_page=100&page=1",
        json=response_json,
    )
    m.get(
        f"{comments_base_url}?per_page=100",
        json=response_json,
    )
    m.get(
        f"{comments_base_url}?per_page=1",
        json=response_json[:1],
    )


def mock_get_file(m: Mocker, s: Settings, data: bytes, ref: str, resolved_hash: str | None = None) -> None:
    mock_repo(m, s)
    m.get(
        f"{s.api_url}/repos/{s.repository}/contents/{s.lockfile_path}?ref={ref}",
        content=data,
    )


def mock_resolve_commit_hashes(
    m: Mocker,
    s: Settings,
    head_hash: str | None = None,
    base_hash: str | None = None,
) -> None:
    response_json = {
        "data": {
            "repository": {
                "head": {"target": {"oid": head_hash}} if head_hash else None,
                "base": {"target": {"oid": base_hash}} if base_hash else None,
            }
        }
    }
    m.post(
        f"{s.api_url}/graphql",
        json=response_json,
    )


def mock_repo(m: Mocker, s: Settings) -> None:
    repo_url = f"{s.api_url}/repos/{s.repository}"
    m.get(
        repo_url,
        json={
            "id": 1,
            "name": s.repository.split("/")[-1],
            "full_name": s.repository,
            "url": repo_url,
            "contents_url": f"{repo_url}/contents/{{+path}}",
            "issues_url": f"{repo_url}/issues{{/number}}",
            "pulls_url": f"{repo_url}/pulls{{/number}}",
        },
    )


def mock_issue(m: Mocker, s: Settings, pr_num: str | None = None) -> None:
    effective_pr_num = pr_num or s.pr_num
    assert effective_pr_num is not None
    issue_url = f"{s.api_url}/repos/{s.repository}/issues/{effective_pr_num}"
    m.get(
        issue_url,
        json={
            "id": int(effective_pr_num),
            "number": int(effective_pr_num),
            "url": issue_url,
            "comments_url": f"{issue_url}/comments",
        },
    )


def mock_issue_comment(m: Mocker, s: Settings, comment_id: int, body: str) -> None:
    comment_url = f"{s.api_url}/repos/{s.repository}/issues/comments/{comment_id}"
    m.get(
        comment_url,
        json={"id": comment_id, "url": comment_url, "body": body, "user": {"id": 41898282}},
    )


def create_settings(
    repository: str = "user/repo",
    lockfile_path: str = "poetry.lock",
    token: str = "foobar",
    api_url: str = "http://localhost:80",
) -> Settings:
    return GitHubActionsSettings(
        event_name="pull_request",
        ref="refs/pull/1/merge",
        head_ref="refs/heads/deps-update",
        repository=repository,
        token=token,
        base_ref="main",
        lockfile_path=lockfile_path,
        api_url=api_url,
    )
