name: Build and Check
on:
  pull_request:

permissions: {}

jobs:
  build-check:
    runs-on: ubuntu-latest
    name: Dependencies
    timeout-minutes: 15
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.11'
      - name: Install and configure Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: '2.3.2'
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: Ruff format
        run: poetry run ruff format --check .
      - name: Ruff check
        run: poetry run ruff check .
      - name: Mypy
        run: poetry run mypy .
      - name: Pytest
        run: poetry run pytest .
  diff-lockfile-main:
    runs-on: ubuntu-latest
    name: Dogfooding main
    continue-on-error: true
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: poetry.lock
          persist-credentials: false
      - name: Diff poetry.lock
        env:
          DEBUG_MODE: 1
        uses: | # zizmor: ignore[unpinned-uses] It's safe to use main on our own repo.
          target/diff-poetry-lock@main
